"""assay — deterministic work-session completion gate.

Faithful Python port of the SpecForge ``@specforge/assayforge`` engine.

``assay(context, options)`` runs four independent checks over the normalized
work-session event tables, then a single gate ``passed = no finding has
severity 'error'``. Two modes: ``action`` (computes ``next_step``) and
``check`` (computes a ``summary``). Output is verified byte-for-byte against
the reference TypeScript engine via differential tests.
"""

from __future__ import annotations

from . import runtime, types
from .config import (
    HARDCODED_DEFAULTS,
    SAFE_RANGES,
    AssayforgeConfigSchema,
    ConfigValidationError,
    DeepPartial,
    config_hash,
    load_config,
    load_defaults,
    merge_config,
    validate_config,
    validate_safe_ranges,
)
from .runtime.assay import assay
from .runtime.checks import (
    CHECK_REGISTRY,
    CheckFn,
    CheckOutput,
    CheckRunOptions,
    acceptance_coverage_check,
    file_action_coverage_check,
    get_file_action_severity,
    implementation_coverage_check,
    test_result_presence_check,
)
from .runtime.enums import ASSAY_ACTION_SEQUENCE, ASSAY_ACTIONS, AssayAction
from .runtime.field_declarations import is_field_na
from .runtime.guidance import (
    CheckSummaryComposeInput,
    GuidanceVerbosity,
    NextStepComposeOptions,
    NextStepTemplateKey,
    compose_check_summary,
    compose_finding_guidance,
    compose_next_step_guidance,
    finding_templates,
    interpolate,
    next_step_key,
    next_step_templates,
)
from .runtime.id_generator import IdGenerator, deterministic_id_generator, uuid_id_generator
from .runtime.issues import (
    FileChangeIssueEntry,
    TestResultIssueEntry,
    find_open_file_change_issues,
    find_open_test_result_issues,
)
from .runtime.next_step import action_applies, applicable_actions, resolve_next_step
from .runtime.operations_registry import (
    OPERATION_NAMES,
    OPERATIONS,
    OperationDef,
    OperationName,
    is_operation_name,
)
from .runtime.progress import (
    compute_acceptance_progress,
    compute_file_action_progress,
    compute_impl_step_progress,
    compute_test_result_progress,
    is_check_imp_step_complete,
)
from .runtime.types import (
    AcceptanceCriterion,
    AssayCheckType,
    AssayContext,
    AssayforgeConfig,
    AssayMode,
    AssayOptions,
    AssayResult,
    AssayResultMeta,
    CheckBaseConfig,
    CheckModeSummary,
    CheckProgress,
    CheckResult,
    FieldDeclaration,
    FileActionCoverageConfig,
    FileChangeIssue,
    Finding,
    FindingGuidance,
    FindingSeverity,
    ImplementationStep,
    NextStep,
    NextStepGuidance,
    NextStepReason,
    SeverityOverride,
    TestResultIssue,
    TestResultPresenceConfig,
    TestSpecification,
    Ticket,
    WorkSession,
    WorkSessionAcceptanceCheck,
    WorkSessionFileChange,
    WorkSessionImplStepCompletion,
    WorkSessionTestResult,
)
from .runtime.version import ENGINE_VERSION

__version__ = "0.1.0"

__all__ = [
    "ASSAY_ACTIONS",
    "ASSAY_ACTION_SEQUENCE",
    "CHECK_REGISTRY",
    "ENGINE_VERSION",
    "HARDCODED_DEFAULTS",
    "OPERATIONS",
    "OPERATION_NAMES",
    "SAFE_RANGES",
    "AcceptanceCriterion",
    "AssayAction",
    "AssayCheckType",
    "AssayContext",
    "AssayMode",
    "AssayOptions",
    "AssayResult",
    "AssayResultMeta",
    "AssayforgeConfig",
    "AssayforgeConfigSchema",
    "CheckBaseConfig",
    "CheckFn",
    "CheckModeSummary",
    "CheckOutput",
    "CheckProgress",
    "CheckResult",
    "CheckRunOptions",
    "CheckSummaryComposeInput",
    "ConfigValidationError",
    "DeepPartial",
    "FieldDeclaration",
    "FileActionCoverageConfig",
    "FileChangeIssue",
    "FileChangeIssueEntry",
    "Finding",
    "FindingGuidance",
    "FindingSeverity",
    "GuidanceVerbosity",
    "IdGenerator",
    "ImplementationStep",
    "NextStep",
    "NextStepComposeOptions",
    "NextStepGuidance",
    "NextStepReason",
    "NextStepTemplateKey",
    "OperationDef",
    "OperationName",
    "SeverityOverride",
    "TestResultIssue",
    "TestResultIssueEntry",
    "TestResultPresenceConfig",
    "TestSpecification",
    "Ticket",
    "WorkSession",
    "WorkSessionAcceptanceCheck",
    "WorkSessionFileChange",
    "WorkSessionImplStepCompletion",
    "WorkSessionTestResult",
    "__version__",
    "acceptance_coverage_check",
    "action_applies",
    "applicable_actions",
    "assay",
    "compose_check_summary",
    "compose_finding_guidance",
    "compose_next_step_guidance",
    "compute_acceptance_progress",
    "compute_file_action_progress",
    "compute_impl_step_progress",
    "compute_test_result_progress",
    "config_hash",
    "deterministic_id_generator",
    "file_action_coverage_check",
    "find_open_file_change_issues",
    "find_open_test_result_issues",
    "finding_templates",
    "get_file_action_severity",
    "implementation_coverage_check",
    "interpolate",
    "is_check_imp_step_complete",
    "is_field_na",
    "is_operation_name",
    "load_config",
    "load_defaults",
    "merge_config",
    "next_step_key",
    "next_step_templates",
    "resolve_next_step",
    "runtime",
    "test_result_presence_check",
    "types",
    "uuid_id_generator",
    "validate_config",
    "validate_safe_ranges",
]
